name: Perform Mixeway Scan
jobs:
 mixeway-scan:
 name: Mixeway Scanning
 runs-on: ubuntu-latest
 steps:
 - uses: actions/checkout@v1
 - name: Prepare variables
 id: vars
 shell: bash
 run: |
 echo "##[set-output name=branch;]$(echo
${GITHUB_REF#refs/heads/})"
 echo "::set-output name=sha_short::$(git rev-parse HEAD)"
 - name: Prepare Mixeway docker image
 run: |
 docker pull m

- name: Run Scan
      run: |
        docker run \
        -e OSS_USERNAME=igor.matynia@gmail.com \
        -e OSS_KEY=sonatype_pat_G6Rs6_spsfs267RPXgKsPhZ0s_zcXgXNbGA3XC1J26Fco_p1 \
        -e MIXEWAY_URL=https://hub.mixeway.io \
        -e MIXEWAY_KEY=452c6cc1-7bef-408e-8912-b3082892878b \
        -e MIXEWAY_PROJECT_ID=194 \
        -e MODE=STANDALONE \
        -e MIXEWAY_PROJECT_NAME=imatynia_lab_secure_app \
        -e COMMIT_ID=${{ steps.vars.outputs.sha_short }} \
        -e BRANCH=${{ steps.vars.outputs.branch }} \
        -v ${{ github.workspace }}:/opt/sources \
        mixeway/scanner:latest
